//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Person
{
    public string StudentID { get; set; }
    public string StudentName { get; set; }
    public string Period { get; set; }
    public string Answer_1 { get; set; }
    public string Answer_2 { get; set; }
    public string Answer_3 { get; set; }
    public string Answer_4 { get; set; }
    public string Answer_5 { get; set; }
    public string Answer_6 { get; set; }
    public string Answer_7 { get; set; }
    public string Answer_8 { get; set; }
    public string Answer_9 { get; set; }
    public string Answer_10 { get; set; }
    public string Answer_11 { get; set; }
}
